name: CI
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
jobs:
  build-linux:
    uses: ./.github/workflows/linux-build.yml
    with:
      configuration: Release

  build-windows:
    uses: ./.github/workflows/window-build.yml
    with:
      configuration: Release