# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: QubicCoreLite-Linux

on:
  workflow_call:
    inputs:
      configuration:
        description: "Build configuration"
        required: true
        default: "Release"
        type: string

env:
  BUILD_DIR: build
  BUILD_CONFIGURATION: ${{ github.event.inputs.configuration || 'Release' }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-path: ${{ steps.build.outputs.path }}
    steps:
      # Checkout source
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install CMake and dependencies
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y build-essential clang cmake nasm
          sudo apt install -y libc++-dev libc++abi-dev zip unzip

      # Configure the project
      - name: Configure with CMake
        run: |
          cmake -S . -B ${{ env.BUILD_DIR }} \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_CONFIGURATION }} \
            -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ \
            -DBUILD_TESTS:BOOL=OFF \
            -DBUILD_BINARY:BOOL=ON \
            -DENABLE_AVX512=OFF \
            -DUSE_SANITIZER=OFF

      # Build the project
      - name: Build with Make
        run: cmake --build ${{ env.BUILD_DIR }} --config ${{ env.BUILD_CONFIGURATION }} -- -j$(nproc)

      # Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: QubicLiteLinuxBuild-${{ env.BUILD_CONFIGURATION }}
          path: |
            ${{ env.BUILD_DIR }}